#!/bin/bash
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v55_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=256 --hidden_layers=4
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v57_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=64 --hidden_layers=4
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v58_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=32 --hidden_layers=4
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v59_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=256 --hidden_layers=2
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v60_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=128 --hidden_layers=2
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v61_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=64 --hidden_layers=2
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v62_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=32 --hidden_layers=2
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v63_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=256 --hidden_layers=6
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v64_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=128 --hidden_layers=6
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v65_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=64 --hidden_layers=6
python3 ml4_wcut_diff.py --save_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v66_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_validate_combined.npy" --training_weight_cut=1.5e-5 --lr=1e-4 --hidden_dim=32 --hidden_layers=6