#!/bin/bash

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v14_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v14_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v15_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v15_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v16_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v16_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v17_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v17_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v18_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v18_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v19_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v19_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v24_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_24_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v25_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_25_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v26_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_26_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v27_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_27_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05