#!/bin/bash

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data169p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate169p5.npy" --info="Sample Data : mt= 169.5 GeV" --weight_cut=1.5e-05

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data170p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate170p5.npy" --info="Sample Data : mt= 170.5 GeV" --weight_cut=1.5e-05

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data171p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate171p5.npy" --info="Sample Data : mt= 171.5 GeV" --weight_cut=1.5e-05

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data173p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate173p5.npy" --info="Sample Data : mt= 173.5 GeV" --weight_cut=1.5e-05

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data174p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate174p5.npy" --info="Sample Data : mt= 174.5 GeV" --weight_cut=1.5e-05

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data175p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate175p5.npy" --info="Sample Data : mt= 175.5 GeV" --weight_cut=1.5e-05

## 29

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v29_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_29_old_data169p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate169p5.npy" --info="Sample Data : mt= 169.5 GeV" --weight_cut=1.5e-05

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v29_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_29_old_data170p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate170p5.npy" --info="Sample Data : mt= 170.5 GeV" --weight_cut=1.5e-05

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v29_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_29_old_data171p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate171p5.npy" --info="Sample Data : mt= 171.5 GeV" --weight_cut=1.5e-05

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v29_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_29_old_data173p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate173p5.npy" --info="Sample Data : mt= 173.5 GeV" --weight_cut=1.5e-05

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v29_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_29_old_data174p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate174p5.npy" --info="Sample Data : mt= 174.5 GeV" --weight_cut=1.5e-05

python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v29_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_29_old_data175p5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate175p5.npy" --info="Sample Data : mt= 175.5 GeV" --weight_cut=1.5e-05