#!/bin/bash

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v14_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v14_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v15_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v15_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v16_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v16_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v17_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v17_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v18_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v18_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v19_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v19_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v22_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_22_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v23_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_23_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v24_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_24_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v25_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_25_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_30_older/alpha1/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_0p0" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_30_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot_.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v29_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_29_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v29_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_29_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v34_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_34_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v35_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_35_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v36_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_36_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v37_older/alpha2/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_37_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v38_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_38_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v42_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_42_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v45_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_45_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v46_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_46_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined_v2.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v47_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_47_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v48_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_48_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined_v2.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v49_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_49_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v50_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_50_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v51_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_51_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_vSF_TEST_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_SF_TEST_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy"  --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy"  --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

