#!/bin/bash
#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v3" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV"

# python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v3_173_5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar/ML_Data_train.npy"  --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_173p5/ML_Data_validate.npy" --info="Sample Data : mt= 173.5 GeV"

# python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v3_171_5" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar/ML_Data_train.npy"  --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_171p5/ML_Data_validate.npy" --info="Sample Data : mt= 171.5 GeV"

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v3_without_first_bins" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV"


#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v4_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_3e-06" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v3_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=3e-06


#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v4_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_3e-06" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v3_171p5_5_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_171p5/ML_Data_validate.npy" --info="Sample Data : mt= 171.5 GeV" --weight_cut=3e-06


#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v4_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_3e-06" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v3_173p5_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_173p5/ML_Data_validate.npy" --info="Sample Data : mt= 173.5 GeV" --weight_cut=3e-06


python3 ml5c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v5/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v5_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV"