#!/bin/bash
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_70_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_70_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_71_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_71_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_72_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_72_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_73_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_73_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_74_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_74_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_75_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_75_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_76_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_76_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_77_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_77_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_78_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_78_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_79_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_79_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_80_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_80_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_81_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_81_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_82_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_82_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_83_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_83_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_84_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_84_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_85_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_85_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05
# python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_86_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_86_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05


python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_90_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_90_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_91_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_91_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_92_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_92_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e159of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_93_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_93_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_94_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_94_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_95_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_95_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e189of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_96_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_96_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_97_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_97_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_98_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_98_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_99_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_99_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_100_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_100_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_101_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_101_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_102_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_102_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_103_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_103_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e250of250.npy" --weight_cut=1.5e-05
python3 ml_plot7.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_104_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_104_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e126of250.npy" --weight_cut=1.5e-05