#!/bin/bash

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v14_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v14_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v15_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v15_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v16_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v16_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v17_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v17_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v18_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v18_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/17_01/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml4c_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v19_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_v19_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v22_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_22_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v23_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_23_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v24_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_24_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v25_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_25_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_30_older/alpha1/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_0p0" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_30_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v3_with_mass/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v29_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_29_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v29_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_29_old_data" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml5_plot.py --load_model_path="/scratch-cbe/users/simon.hablas/MLUnfolding/models/EEEC_v28_older/UL2018/nAK82p-AK8pt/shortsidep1/50/all_ptcut5GeV/weight_cut_1p5e-05" --plot_dir="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_28_old_data173p5nonsense" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_train.npy" --val="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/TTbar_older/ML_Data_validate173p5nonsense.npy" --info="Sample Data : mt= 172.5 GeV" --weight_cut=1.5e-05

#python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_42_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy"  --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_42_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e100of100.npy" --weight_cut=1.5e-05 --shift=0

#python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_47_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy"  --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_47_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e170of200.npy" --weight_cut=1.5e-05 --shift=0

#python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_48_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined_v2.npy"  --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_48_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e170of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_55_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_55_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_56_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_56_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_57_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_57_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_58_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_58_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_59_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_59_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_60_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_60_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_61_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_61_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_62_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_62_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_63_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_63_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_64_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_64_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_65_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_65_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0

python3 ml_plot6.py --val="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_66_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/val.npy" --train="/scratch-cbe/users/simon.hablas/MLUnfolding/data/EEEC_v4/UL2018/nAK82p-AK8pt/shortsidep1/50/ptcut5GeV/ML_Data_train_combined.npy" --unfolded="/groups/hephy/cms/simon.hablas/www/MLUnfolding/plots/EEEC_66_old_data/weight_cut_1p5e-05/stack_with_sample_cut/data/m10f3e200of200.npy" --weight_cut=1.5e-05 --shift=0
